'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
	Imports System.Data.Entity
	Imports System.Data.Entity.Infrastructure
Namespace DropDownRemoteData.Models

	Partial Public Class NorthwindEntities
		Inherits DbContext
		Public Sub New()
			MyBase.New("name=NorthwindEntities")
		End Sub

		Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
			Throw New UnintentionalCodeFirstException()
		End Sub

		Private privateOrders As DbSet(Of Order)
		Public Overridable Property Orders() As DbSet(Of Order)
			Get
				Return privateOrders
			End Get
			Set(ByVal value As DbSet(Of Order))
				privateOrders = value
			End Set
		End Property
	End Class
End Namespace
